name: useAppBadge

on: [push]
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Install
        run: pnpm install
      - name: Build standardized-app-badge
        run: pnpm -C packages/standardized-app-badge build-ci
      - name: Build use-app-badge
        run: pnpm -C packages/use-app-badge build-ci
      - name: Build Demo
        run: pnpm -C packages/use-app-badge-demo build-site
      - name: Publish Demo
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: packages/use-app-badge-demo/out
          commit-message: Updates
